### PR TITLE
fix bug. when use x509_signing_key.

### PR DESCRIPTION
**Pull request by hiyosi**
fix return object.

When I tried to use 'client_x509_signing_key' option, got an error occurred as follows.
```
ArgumentError - wrong number of arguments (3 for 1):
  json-jwt (0.7.1) lib/json/jws.rb:74:in `verify'
  json-jwt (0.7.1) lib/json/jws.rb:74:in `valid?'
  json-jwt (0.7.1) lib/json/jws.rb:20:in `verify'
  json-jwt (0.7.1) lib/json/jwt.rb:59:in `verify'
  json-jwt (0.7.1) lib/json/jwt.rb:98:in `decode'
  openid_connect (0.8.1) lib/openid_connect/response_object/id_token.rb:60:in `decode'
  ...
```

library expects ```OpenSSL::PKey::RSA``` object.
(https://github.com/nov/json-jwt/blob/master/lib/json/jws.rb#L72-L74)

### CODE REVIEW

**Comment by hiyosi** [comment]
@jjbohn Please review this PR.

**Comment by jjbohn** [comment]
Taking a look. Thanks. Might take me a day or two to check it out. Need to dig through and make sure I know all the implications.

**Comment by jjbohn** [comment]
@niftyn8 you gotta minute to double check this? I've been backed up all week and can't find the time to validate.

**Comment by hiyosi** [comment]
Hi, Have you made any progress about this PR?

**Comment by jjbohn** [comment]
@hiyosi Sorry, no I hadn't. Being a terrible steward. I'll give it a second look at lunch today. Thanks

**Comment by hiyosi** [comment]
@jjbohn Thanks :+1: 
Best regards.

**Comment by jjbohn** [comment]
:+1:

**Comment by jjbohn** [comment]
Thanks again and sorry for the huge delay.

**Pull request merged**
