### PR TITLE
Drop support for deprected ruby versions

### PR DESCRIPTION
**Pull request by tfluehmann**

### CODE REVIEW

**Comment by tfluehmann** [comment]
rbx fails, bugfix in travis is open https://github.com/rvm/rvm/issues/3651

**Comment by m0n9oose** [comment]
I thought maintenance of this repository was stopped. Wasn't it?

**Comment by tfluehmann** [comment]
@m0n9oose yes probably, I thougth you have access to merge.
Do you just maintain your fork?
Where should people contribute?

**Comment by m0n9oose** [comment]
@tfluehmann  no, I just forked this repo, add some code and leave it alone.

Right now I'm not working with this code at all, and there is a strong possibility that I wont work with it anymore.

So I think you can fork one of these repos and continue this work by yourself.

**Comment by tfluehmann** [comment]
@m0n9oose OK cool, I'll do that, thanks for the reply

**Pull request closed without merging**
