### PR TITLE
bump up openid-connect version

### PR DESCRIPTION
**Pull request by hiyosi**
* bump up 'openid-connect' version.
* when 'kid' parameter includes in the IDToken header, to use it for verify.

----
* it will fail by reason of the following when tested in JRuby.
  * https://github.com/jruby/jruby/issues/1261
* maybe, 'openid_connect' does not support JRuby.

### CODE REVIEW

**Comment by hiyosi** [comment]
Also by this pull request, #36 and #37 are fixed.

**Comment by hiyosi** [comment]
@jjbohn Please review this PR.

**Comment by jjbohn** [comment]
Hey @hiyosi thanks. Just removed the jruby test dependency from travis since I'm not really interested in targeting it anyway and I'd rather see this merged in.

**Comment by hiyosi** [comment]
Thank you for quick response. :+1:

**Pull request merged**
